/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMaquinaRouteImport } from './routes/_authenticated/maquina'
import { Route as AuthenticatedFerramentasRouteImport } from './routes/_authenticated/ferramentas'
import { Route as AuthenticatedPecasIndexRouteImport } from './routes/_authenticated/pecas.index'
import { Route as AuthenticatedPecasImportarRouteImport } from './routes/_authenticated/pecas.importar'
import { Route as AuthenticatedPecasIdRouteImport } from './routes/_authenticated/pecas.$id'
import { Route as AuthenticatedPecasIdCncRouteImport } from './routes/_authenticated/pecas.$id.cnc'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMaquinaRoute = AuthenticatedMaquinaRouteImport.update({
  id: '/_authenticated/maquina',
  path: '/maquina',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFerramentasRoute =
  AuthenticatedFerramentasRouteImport.update({
    id: '/_authenticated/ferramentas',
    path: '/ferramentas',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPecasIndexRoute = AuthenticatedPecasIndexRouteImport.update({
  id: '/_authenticated/pecas/',
  path: '/pecas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPecasImportarRoute =
  AuthenticatedPecasImportarRouteImport.update({
    id: '/_authenticated/pecas/importar',
    path: '/pecas/importar',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPecasIdRoute = AuthenticatedPecasIdRouteImport.update({
  id: '/_authenticated/pecas/$id',
  path: '/pecas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPecasIdCncRoute = AuthenticatedPecasIdCncRouteImport.update({
  id: '/cnc',
  path: '/cnc',
  getParentRoute: () => AuthenticatedPecasIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/ferramentas': typeof AuthenticatedFerramentasRoute
  '/maquina': typeof AuthenticatedMaquinaRoute
  '/': typeof AuthenticatedIndexRoute
  '/pecas/$id': typeof AuthenticatedPecasIdRouteWithChildren
  '/pecas/importar': typeof AuthenticatedPecasImportarRoute
  '/pecas/': typeof AuthenticatedPecasIndexRoute
  '/pecas/$id/cnc': typeof AuthenticatedPecasIdCncRoute
}
export interface FileRoutesByTo {
  '/ferramentas': typeof AuthenticatedFerramentasRoute
  '/maquina': typeof AuthenticatedMaquinaRoute
  '/': typeof AuthenticatedIndexRoute
  '/pecas/$id': typeof AuthenticatedPecasIdRouteWithChildren
  '/pecas/importar': typeof AuthenticatedPecasImportarRoute
  '/pecas': typeof AuthenticatedPecasIndexRoute
  '/pecas/$id/cnc': typeof AuthenticatedPecasIdCncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/ferramentas': typeof AuthenticatedFerramentasRoute
  '/_authenticated/maquina': typeof AuthenticatedMaquinaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/pecas/$id': typeof AuthenticatedPecasIdRouteWithChildren
  '/_authenticated/pecas/importar': typeof AuthenticatedPecasImportarRoute
  '/_authenticated/pecas/': typeof AuthenticatedPecasIndexRoute
  '/_authenticated/pecas/$id/cnc': typeof AuthenticatedPecasIdCncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/ferramentas'
    | '/maquina'
    | '/'
    | '/pecas/$id'
    | '/pecas/importar'
    | '/pecas/'
    | '/pecas/$id/cnc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ferramentas'
    | '/maquina'
    | '/'
    | '/pecas/$id'
    | '/pecas/importar'
    | '/pecas'
    | '/pecas/$id/cnc'
  id:
    | '__root__'
    | '/_authenticated/ferramentas'
    | '/_authenticated/maquina'
    | '/_authenticated/'
    | '/_authenticated/pecas/$id'
    | '/_authenticated/pecas/importar'
    | '/_authenticated/pecas/'
    | '/_authenticated/pecas/$id/cnc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedFerramentasRoute: typeof AuthenticatedFerramentasRoute
  AuthenticatedMaquinaRoute: typeof AuthenticatedMaquinaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPecasIdRoute: typeof AuthenticatedPecasIdRouteWithChildren
  AuthenticatedPecasImportarRoute: typeof AuthenticatedPecasImportarRoute
  AuthenticatedPecasIndexRoute: typeof AuthenticatedPecasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/maquina': {
      id: '/_authenticated/maquina'
      path: '/maquina'
      fullPath: '/maquina'
      preLoaderRoute: typeof AuthenticatedMaquinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ferramentas': {
      id: '/_authenticated/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof AuthenticatedFerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pecas/': {
      id: '/_authenticated/pecas/'
      path: '/pecas'
      fullPath: '/pecas/'
      preLoaderRoute: typeof AuthenticatedPecasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pecas/importar': {
      id: '/_authenticated/pecas/importar'
      path: '/pecas/importar'
      fullPath: '/pecas/importar'
      preLoaderRoute: typeof AuthenticatedPecasImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pecas/$id': {
      id: '/_authenticated/pecas/$id'
      path: '/pecas/$id'
      fullPath: '/pecas/$id'
      preLoaderRoute: typeof AuthenticatedPecasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pecas/$id/cnc': {
      id: '/_authenticated/pecas/$id/cnc'
      path: '/cnc'
      fullPath: '/pecas/$id/cnc'
      preLoaderRoute: typeof AuthenticatedPecasIdCncRouteImport
      parentRoute: typeof AuthenticatedPecasIdRoute
    }
  }
}

interface AuthenticatedPecasIdRouteChildren {
  AuthenticatedPecasIdCncRoute: typeof AuthenticatedPecasIdCncRoute
}

const AuthenticatedPecasIdRouteChildren: AuthenticatedPecasIdRouteChildren = {
  AuthenticatedPecasIdCncRoute: AuthenticatedPecasIdCncRoute,
}

const AuthenticatedPecasIdRouteWithChildren =
  AuthenticatedPecasIdRoute._addFileChildren(AuthenticatedPecasIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedFerramentasRoute: AuthenticatedFerramentasRoute,
  AuthenticatedMaquinaRoute: AuthenticatedMaquinaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPecasIdRoute: AuthenticatedPecasIdRouteWithChildren,
  AuthenticatedPecasImportarRoute: AuthenticatedPecasImportarRoute,
  AuthenticatedPecasIndexRoute: AuthenticatedPecasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
